bf.AppStru.data = [            
     {
    	 id:'all',
    	 name:'门户和分类'
     },
     {
    	 id:'section',
    	 name:"板块一览",
    	 children:[
	           {
	        	   id:'list',
	        	   name:"板块列表"
	           },
	           {
	        	   id:'list_json',
	        	   name:"专辑列表（JSON）"
	           }
	      ]
     },
     {
			id:'album',
			name:"专辑一览",
	    	children:[
				{
					id:'list',
					name:"专辑列表"
				},
				{
					id:'list_json',
					name:"专辑列表（JSON）"
				}
	    	 ]
     },
     {
    	 id:'show_video',
    	 name:'视频',
    	 children:[
			{
				id:'list',
				name:"视频列表"
			},
			{
				id:'list_json',
				name:"视频列表（JSON）"
			}
    	 ]
     },
     {
    	 id:'show_audio',
    	 name:'音频',
    	 children:[
			{
				id:'list',
				name:"音频列表"
			},
			{
				id:'list_json',
				name:"音频列表（JSON）"
			}
    	 ]
     },
     {
     	id :'show_article',
     	name:'文章',
     	children:[
   			{
   				id:'list',
   				name:"文章列表"
   			},
   			{
   				id:'list_json',
   				name:"文章列表（JSON）"
   			}
       	 ]
     },
     {
    	 id :'admin',
    	 name:'后台管理'
     },
     {
    	 id : 'help',
    	 name :'帮助',
    	 children:[
           {
        	   id :"document",
        	   name:'文档'
           },
           {
				id:'feedback',
				name:"反馈"
			},{
				id:'sitemap',
				name:"网站地图"
			},{
				 id:'disclaimer',
				 name:"服务条款"
			}
    	 ]
     }
];

